// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: message.sql

package repo

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (thread_id, sender_id, receiver_id, message_text)
VALUES ($1, $2, $3, $4)
RETURNING message_id, thread_id, sender_id, receiver_id, message_text, is_deleted, status, sent_at
`

type CreateMessageParams struct {
	ThreadID    string `json:"thread_id"`
	SenderID    string `json:"sender_id"`
	ReceiverID  string `json:"receiver_id"`
	MessageText string `json:"message_text"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ThreadID,
		arg.SenderID,
		arg.ReceiverID,
		arg.MessageText,
	)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.ThreadID,
		&i.SenderID,
		&i.ReceiverID,
		&i.MessageText,
		&i.IsDeleted,
		&i.Status,
		&i.SentAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payment (payer_id, target_user_id, thread_id, amount, external_reference)
VALUES ($1, $2, $3, $4, $5)
RETURNING payment_id, payer_id, target_user_id, thread_id, phone, amount, status, provider, reference, external_reference, created_at
`

type CreatePaymentParams struct {
	PayerID           string         `json:"payer_id"`
	TargetUserID      string         `json:"target_user_id"`
	ThreadID          string         `json:"thread_id"`
	Amount            pgtype.Numeric `json:"amount"`
	ExternalReference string         `json:"external_reference"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.PayerID,
		arg.TargetUserID,
		arg.ThreadID,
		arg.Amount,
		arg.ExternalReference,
	)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.PayerID,
		&i.TargetUserID,
		&i.ThreadID,
		&i.Phone,
		&i.Amount,
		&i.Status,
		&i.Provider,
		&i.Reference,
		&i.ExternalReference,
		&i.CreatedAt,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO thread (initiator_id, target_user_id, topic)
VALUES ($1, $2, $3)
RETURNING thread_id, initiator_id, target_user_id, topic, is_unlocked, created_at
`

type CreateThreadParams struct {
	InitiatorID  string `json:"initiator_id"`
	TargetUserID string `json:"target_user_id"`
	Topic        string `json:"topic"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread, arg.InitiatorID, arg.TargetUserID, arg.Topic)
	var i Thread
	err := row.Scan(
		&i.ThreadID,
		&i.InitiatorID,
		&i.TargetUserID,
		&i.Topic,
		&i.IsUnlocked,
		&i.CreatedAt,
	)
	return i, err
}

const filterUsersByPreferences = `-- name: FilterUsersByPreferences :many
SELECT 
 COALESCE(user_id, '') AS user_id,
  COALESCE(fname, '') AS fname,
  COALESCE(lname, '') AS lname,
  COALESCE(birthdate, '2000-01-01') AS birthdate,
  COALESCE(phoneno, '') AS phoneno,
  COALESCE(email, '') AS email,
  COALESCE(bio, '') AS bio,
  COALESCE(habbits, '{}'::jsonb) AS habbits,
  COALESCE(profile_picture, '') AS profile_picture,
  COALESCE(created_at, now()) AS created_at
  FROM users
WHERE habbits @> $1::jsonb
`

type FilterUsersByPreferencesRow struct {
	UserID         string           `json:"user_id"`
	Fname          string           `json:"fname"`
	Lname          string           `json:"lname"`
	Birthdate      pgtype.Date      `json:"birthdate"`
	Phoneno        string           `json:"phoneno"`
	Email          string           `json:"email"`
	Bio            string           `json:"bio"`
	Habbits        json.RawMessage  `json:"habbits"`
	ProfilePicture string           `json:"profile_picture"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) FilterUsersByPreferences(ctx context.Context, dollar_1 []byte) ([]FilterUsersByPreferencesRow, error) {
	rows, err := q.db.Query(ctx, filterUsersByPreferences, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterUsersByPreferencesRow{}
	for rows.Next() {
		var i FilterUsersByPreferencesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Fname,
			&i.Lname,
			&i.Birthdate,
			&i.Phoneno,
			&i.Email,
			&i.Bio,
			&i.Habbits,
			&i.ProfilePicture,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT 
  COALESCE(user_id, '') AS user_id,
  COALESCE(fname, '') AS fname,
  COALESCE(lname, '') AS lname,
  COALESCE(birthdate, '2000-01-01') AS birthdate,
  COALESCE(phoneno, '') AS phoneno,
  COALESCE(email, '') AS email,
  COALESCE(bio, '') AS bio,
  COALESCE(habbits, '{}'::jsonb) AS habbits,
  COALESCE(profile_picture, '') AS profile_picture,
  COALESCE(created_at, now()) AS created_at
FROM users
WHERE user_id != $1
`

type GetAllUsersRow struct {
	UserID         string           `json:"user_id"`
	Fname          string           `json:"fname"`
	Lname          string           `json:"lname"`
	Birthdate      pgtype.Date      `json:"birthdate"`
	Phoneno        string           `json:"phoneno"`
	Email          string           `json:"email"`
	Bio            string           `json:"bio"`
	Habbits        json.RawMessage  `json:"habbits"`
	ProfilePicture string           `json:"profile_picture"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetAllUsers(ctx context.Context, userID string) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUsersRow{}
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Fname,
			&i.Lname,
			&i.Birthdate,
			&i.Phoneno,
			&i.Email,
			&i.Bio,
			&i.Habbits,
			&i.ProfilePicture,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNamesOnThread = `-- name: GetNamesOnThread :many
SELECT u.user_id, u.fname, u.lname, t.is_unlocked
FROM thread t
JOIN users u ON t.target_user_id = u.user_id
WHERE t.thread_id = $1
`

type GetNamesOnThreadRow struct {
	UserID     string  `json:"user_id"`
	Fname      *string `json:"fname"`
	Lname      *string `json:"lname"`
	IsUnlocked bool    `json:"is_unlocked"`
}

func (q *Queries) GetNamesOnThread(ctx context.Context, threadID string) ([]GetNamesOnThreadRow, error) {
	rows, err := q.db.Query(ctx, getNamesOnThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNamesOnThreadRow{}
	for rows.Next() {
		var i GetNamesOnThreadRow
		if err := rows.Scan(
			&i.UserID,
			&i.Fname,
			&i.Lname,
			&i.IsUnlocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByThreadId = `-- name: GetPaymentByThreadId :one
SELECT payment_id, payer_id, target_user_id, thread_id, phone, amount, status, provider, reference, external_reference, created_at FROM payment
WHERE thread_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPaymentByThreadId(ctx context.Context, threadID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByThreadId, threadID)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.PayerID,
		&i.TargetUserID,
		&i.ThreadID,
		&i.Phone,
		&i.Amount,
		&i.Status,
		&i.Provider,
		&i.Reference,
		&i.ExternalReference,
		&i.CreatedAt,
	)
	return i, err
}

const getThreadBetweenUsers = `-- name: GetThreadBetweenUsers :one
SELECT 
   thread_id,
   initiator_id,
   target_user_id,
   topic,
   is_unlocked,
   created_at
FROM thread
WHERE (initiator_id = $1 AND target_user_id = $2)
`

type GetThreadBetweenUsersParams struct {
	InitiatorID  string `json:"initiator_id"`
	TargetUserID string `json:"target_user_id"`
}

func (q *Queries) GetThreadBetweenUsers(ctx context.Context, arg GetThreadBetweenUsersParams) (Thread, error) {
	row := q.db.QueryRow(ctx, getThreadBetweenUsers, arg.InitiatorID, arg.TargetUserID)
	var i Thread
	err := row.Scan(
		&i.ThreadID,
		&i.InitiatorID,
		&i.TargetUserID,
		&i.Topic,
		&i.IsUnlocked,
		&i.CreatedAt,
	)
	return i, err
}

const getThreadById = `-- name: GetThreadById :many
SELECT thread_id, initiator_id, target_user_id, topic, is_unlocked, created_at 
FROM thread
WHERE initiator_id = $1
`

func (q *Queries) GetThreadById(ctx context.Context, initiatorID string) ([]Thread, error) {
	rows, err := q.db.Query(ctx, getThreadById, initiatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ThreadID,
			&i.InitiatorID,
			&i.TargetUserID,
			&i.Topic,
			&i.IsUnlocked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByFirebaseId = `-- name: GetUserByFirebaseId :one
SELECT user_id, email FROM users
WHERE user_id = $1
LIMIT 1
`

type GetUserByFirebaseIdRow struct {
	UserID string `json:"user_id"`
	Email  string `json:"email"`
}

func (q *Queries) GetUserByFirebaseId(ctx context.Context, userID string) (GetUserByFirebaseIdRow, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseId, userID)
	var i GetUserByFirebaseIdRow
	err := row.Scan(&i.UserID, &i.Email)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT 
  COALESCE(user_id, '') AS user_id,
  COALESCE(fname, '') AS fname,
  COALESCE(lname, '') AS lname,
  COALESCE(birthdate, '2000-01-01') AS birthdate,
  COALESCE(phoneno, '') AS phoneno,
  COALESCE(email, '') AS email,
  COALESCE(bio, '') AS bio,
  COALESCE(habbits, '{}'::jsonb) AS habbits,
  COALESCE(profile_picture, '') AS profile_picture,
  COALESCE(created_at, now()) AS created_at
FROM users
WHERE user_id = $1
LIMIT 1
`

type GetUserByIdRow struct {
	UserID         string           `json:"user_id"`
	Fname          string           `json:"fname"`
	Lname          string           `json:"lname"`
	Birthdate      pgtype.Date      `json:"birthdate"`
	Phoneno        string           `json:"phoneno"`
	Email          string           `json:"email"`
	Bio            string           `json:"bio"`
	Habbits        json.RawMessage  `json:"habbits"`
	ProfilePicture string           `json:"profile_picture"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetUserById(ctx context.Context, userID string) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, userID)
	var i GetUserByIdRow
	err := row.Scan(
		&i.UserID,
		&i.Fname,
		&i.Lname,
		&i.Birthdate,
		&i.Phoneno,
		&i.Email,
		&i.Bio,
		&i.Habbits,
		&i.ProfilePicture,
		&i.CreatedAt,
	)
	return i, err
}

const getUserHabbits = `-- name: GetUserHabbits :one
SELECT habbits
FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserHabbits(ctx context.Context, userID string) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getUserHabbits, userID)
	var habbits json.RawMessage
	err := row.Scan(&habbits)
	return habbits, err
}

const registerUser = `-- name: RegisterUser :one





INSERT INTO users (user_id,email)
VALUES ($1, $2)
RETURNING user_id,email
`

type RegisterUserParams struct {
	UserID string `json:"user_id"`
	Email  string `json:"email"`
}

type RegisterUserRow struct {
	UserID string `json:"user_id"`
	Email  string `json:"email"`
}

// -- name: CreateMessage :one
// INSERT INTO message (thread, sender, content)
// VALUES ($1, $2, $3)
// RETURNING *;
// -- name: GetMessageByID :one
// SELECT * FROM message
// WHERE id = $1;
// -- name: GetMessagesByThread :many
// SELECT * FROM message
// WHERE thread = $1
// ORDER BY created_at DESC;
// -- name: DeleteMessage :exec
// DELETE FROM message
// WHERE id = $1;
func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (RegisterUserRow, error) {
	row := q.db.QueryRow(ctx, registerUser, arg.UserID, arg.Email)
	var i RegisterUserRow
	err := row.Scan(&i.UserID, &i.Email)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payment
SET status = $2,
    phone = $3,
    reference = $4,
    external_reference = $5
WHERE payment_id = $1
RETURNING payment_id, payer_id, target_user_id, thread_id, phone, amount, status, provider, reference, external_reference, created_at
`

type UpdatePaymentStatusParams struct {
	PaymentID         string        `json:"payment_id"`
	Status            PaymentStatus `json:"status"`
	Phone             *string       `json:"phone"`
	Reference         *string       `json:"reference"`
	ExternalReference string        `json:"external_reference"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus,
		arg.PaymentID,
		arg.Status,
		arg.Phone,
		arg.Reference,
		arg.ExternalReference,
	)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.PayerID,
		&i.TargetUserID,
		&i.ThreadID,
		&i.Phone,
		&i.Amount,
		&i.Status,
		&i.Provider,
		&i.Reference,
		&i.ExternalReference,
		&i.CreatedAt,
	)
	return i, err
}

const updateThreadStatus = `-- name: UpdateThreadStatus :one
UPDATE thread
SET is_unlocked = $1
WHERE thread_id = $2
RETURNING thread_id, initiator_id, target_user_id, topic, is_unlocked, created_at
`

type UpdateThreadStatusParams struct {
	IsUnlocked bool   `json:"is_unlocked"`
	ThreadID   string `json:"thread_id"`
}

func (q *Queries) UpdateThreadStatus(ctx context.Context, arg UpdateThreadStatusParams) (Thread, error) {
	row := q.db.QueryRow(ctx, updateThreadStatus, arg.IsUnlocked, arg.ThreadID)
	var i Thread
	err := row.Scan(
		&i.ThreadID,
		&i.InitiatorID,
		&i.TargetUserID,
		&i.Topic,
		&i.IsUnlocked,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    fname = COALESCE($2, fname),
    lname = COALESCE($3, lname),
    email = COALESCE($4, email),
    phoneno = COALESCE($5, phoneno),
    birthdate = COALESCE($6, birthdate),
    bio = COALESCE($7, bio),
    habbits = COALESCE($8, habbits),
    profile_picture = COALESCE($9, profile_picture)
WHERE user_id = $1
RETURNING user_id, fname, lname, birthdate, phoneno, email, bio, habbits, profile_picture, created_at
`

type UpdateUserProfileParams struct {
	UserID         string          `json:"user_id"`
	Fname          *string         `json:"fname"`
	Lname          *string         `json:"lname"`
	Email          string          `json:"email"`
	Phoneno        *string         `json:"phoneno"`
	Birthdate      time.Time       `json:"birthdate"`
	Bio            string          `json:"bio"`
	Habbits        json.RawMessage `json:"habbits"`
	ProfilePicture *string         `json:"profile_picture"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.UserID,
		arg.Fname,
		arg.Lname,
		arg.Email,
		arg.Phoneno,
		arg.Birthdate,
		arg.Bio,
		arg.Habbits,
		arg.ProfilePicture,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Fname,
		&i.Lname,
		&i.Birthdate,
		&i.Phoneno,
		&i.Email,
		&i.Bio,
		&i.Habbits,
		&i.ProfilePicture,
		&i.CreatedAt,
	)
	return i, err
}
