// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Match struct {
	MatchID    string           `json:"match_id"`
	User1ID    *string          `json:"user1_id"`
	User2ID    *string          `json:"user2_id"`
	MatchScore *int32           `json:"match_score"`
	Status     *string          `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Thread struct {
	ID        string           `json:"id"`
	Topic     string           `json:"topic"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	UserID         string           `json:"user_id"`
	Fname          string           `json:"fname"`
	Lname          string           `json:"lname"`
	Birthdate      time.Time        `json:"birthdate"`
	Phoneno        string           `json:"phoneno"`
	Email          string           `json:"email"`
	Password       string           `json:"password"`
	Bio            string           `json:"bio"`
	Preferences    json.RawMessage  `json:"preferences"`
	ProfilePicture *string          `json:"profile_picture"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}
