// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"
	"encoding/json"
)

type Querier interface {
	FilterUsersByPreferences(ctx context.Context, dollar_1 []byte) ([]FilterUsersByPreferencesRow, error)
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetUserByFirebaseId(ctx context.Context, userID string) (GetUserByFirebaseIdRow, error)
	GetUserById(ctx context.Context, userID string) (GetUserByIdRow, error)
	GetUserHabbits(ctx context.Context, userID string) (json.RawMessage, error)
	// -- name: CreateMessage :one
	// INSERT INTO message (thread, sender, content)
	// VALUES ($1, $2, $3)
	// RETURNING *;
	// -- name: GetMessageByID :one
	// SELECT * FROM message
	// WHERE id = $1;
	// -- name: GetMessagesByThread :many
	// SELECT * FROM message
	// WHERE thread = $1
	// ORDER BY created_at DESC;
	// -- name: DeleteMessage :exec
	// DELETE FROM message
	// WHERE id = $1;
	RegisterUser(ctx context.Context, arg RegisterUserParams) (RegisterUserRow, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
