// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
	"encoding/json"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error)
	DeleteMessage(ctx context.Context, messageID string) error
	FilterUsersByPreferences(ctx context.Context, dollar_1 []byte) ([]FilterUsersByPreferencesRow, error)
	GetAllUsers(ctx context.Context, userID string) ([]GetAllUsersRow, error)
	GetMessageByID(ctx context.Context, messageID string) (Message, error)
	GetMessagesByThread(ctx context.Context, threadID string) ([]Message, error)
	GetNamesOnThread(ctx context.Context, threadID string) ([]GetNamesOnThreadRow, error)
	GetPaymentIdByThreadId(ctx context.Context, threadID string) (string, error)
	GetThreadBetweenUsers(ctx context.Context, arg GetThreadBetweenUsersParams) (Thread, error)
	GetThreadById(ctx context.Context, initiatorID string) ([]Thread, error)
	GetUserByFirebaseId(ctx context.Context, userID string) (GetUserByFirebaseIdRow, error)
	GetUserById(ctx context.Context, userID string) (GetUserByIdRow, error)
	GetUserHabbits(ctx context.Context, userID string) (json.RawMessage, error)
	RegisterUser(ctx context.Context, arg RegisterUserParams) (RegisterUserRow, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
